# Generated by Django 5.1.1 on 2024-12-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryhistory',
            name='book_id',
            field=models.IntegerField(max_length=50),
        ),
    ]
